Kariyer/Models/BasvuruSahibi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Kariyer.Models
{
    public class BasvuruSahibi
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string AdSoyad { get; set; } = "";

        [Required]
        [StringLength(10)]
        public string Cinsiyet { get; set; } = "";

       [Required]
       [Range(25,55,ErrorMessage ="bu pozisyona yaş uygun değil")]
       [DisplayName("Yas")]
        public int Yas { get; set; }

        [Required]
        [Range(1, 25, ErrorMessage = "gecersiz")]
        [DisplayName("Toplam Çalışma Yılı")]

        public int ToplamTecrube { get; set; }

      


    }
}

Kariyer/Models/Deneyim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Kariyer.Models
{
    public class Deneyim
    {

        public Deneyim()
        {
           


        }

    [Key]
    public int DeneyimId { get; set; }
    [ForeignKey("BasvuruSahibi")]//önemli
    public int BSId { get; set; }
        public virtual BasvuruSahibi BasvuruSahibi { get; private set; }

        public string FirmaAdlari { get; set; }
        public string CalismaTanimi { get; set; }

        [Required]

        public int CalismaYili { get; set; }


    }  
}

Kariyer/Models/ErrorViewModel.cs
using System;

namespace Kariyer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Kariyer/Controllers/HomeController.cs
using Kariyer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Kariyer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Kariyer/Controllers/KariyerController.cs
using Kariyer.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Kariyer.Models;

namespace Kariyer.Controllers
{
    public class KariyerController : Controller
    {
        private readonly KariyerDbContext _context;

        private readonly IWebHostEnvironment webHost;

        public KariyerController(KariyerDbContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            //_webHost =webHost;
        }

        public IActionResult Index()
        {
            List<BasvuruSahibi> applicants;
            applicants = _context.BasvuruSahibis.ToList();
            return View(applicants);
        }

        [HttpGet]
        public IActionResult Create()
        {
            BasvuruSahibi basvuruSahibi = new BasvuruSahibi();
            return View(basvuruSahibi);
        }

        [HttpPost]
        public IActionResult Create(BasvuruSahibi basvuruSahibi)
        {
            _context.Add(basvuruSahibi);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

Kariyer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Kariyer/Views/Kariyer/Create.cshtml
@model Kariyer.Models.BasvuruSahibi

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BasvuruSahibi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AdSoyad" class="control-label"></label>
                <input asp-for="AdSoyad" class="form-control" />
                <span asp-validation-for="AdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cinsiyet" class="control-label"></label>
                <input asp-for="Cinsiyet" class="form-control" />
                <span asp-validation-for="Cinsiyet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yas" class="control-label"></label>
                <input asp-for="Yas" class="form-control" />
                <span asp-validation-for="Yas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToplamTecrube" class="control-label"></label>
                <input asp-for="ToplamTecrube" class="form-control" />
                <span asp-validation-for="ToplamTecrube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Kariyer/Views/Kariyer/EditPost.cshtml
@model Kariyer.Models.BasvuruSahibi

@{
    ViewData["Title"] = "EditPost";
}

<h1>EditPost</h1>

<h4>BasvuruSahibi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AdSoyad" class="control-label"></label>
                <input asp-for="AdSoyad" class="form-control" />
                <span asp-validation-for="AdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cinsiyet" class="control-label"></label>
                <input asp-for="Cinsiyet" class="form-control" />
                <span asp-validation-for="Cinsiyet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yas" class="control-label"></label>
                <input asp-for="Yas" class="form-control" />
                <span asp-validation-for="Yas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToplamTecrube" class="control-label"></label>
                <input asp-for="ToplamTecrube" class="form-control" />
                <span asp-validation-for="ToplamTecrube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Kariyer/Views/Kariyer/Index.cshtml
@model IEnumerable<Kariyer.Models.BasvuruSahibi>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AdSoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cinsiyet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Yas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToplamTecrube)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AdSoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cinsiyet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToplamTecrube)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Kariyer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kariyer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kariyer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kariyer" asp-action="Index">Kariyer Crud</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Kariyer - <a asp-area="" asp-controller="Kariyer" asp-action="Index">Kariyer CRUD</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>